{
  "hash": "6555ee5ae4488c6402872a0267dae97b",
  "result": {
    "markdown": "---\ntitle: \"DID: Panel Data & Repeated Crossection\"\nsubtitle: \"Using `CSDID[2]` and `JWDID`\"\ndescription: \"I how to use this two commands for the estimation of DID models with repeated crossection and panel data\"\nauthor: \"Fernando Rios-Avila\"\ndate: \"6/14/2023\"\ncategories: \n    - Stata\n    - DID\n    - csdid\n    - jwdid\ndraft: false\nbibliography: references.bib\n\n---\n\n## First Things First\n\n### DID with Multiple Periods and Time Heterogeneity\n\nIf you are reading this, you probably know quite well all the problems associated with the infamous TWFE-DID especification. Nevertheless, its worth a quick recap, in case you are not aware of.\n\nBefore the new literature on DID, whenever people wanted to analyze treatment effects using a difference in differences approach, and had access to data with many periods and many individuals, they would tend to use a model specification that look like this:\n \n$$y_{it} = \\delta_i + \\delta_t + \\gamma \\times trt + e_{it}\n$${#eq-1}\n\n\nWhere $trt$ was a dummy variable that would take the value of 1 for treated units after the treatment was implemented, and zero otherwise. The idea was that all units with $trt=0$ (those not yet treated) would be used used as controls. In this specification, one is also controlling for time fixed effects $\\delta_t$ as well as individual (or group) fixed effects $\\delta_i$.\n\nThis specification was considered a generalization of the simple 2x2 DID design:\n\n$$\ny = \\delta_0 + \\delta_1 post+ \\delta_2 treat + \\gamma \\ (post\\times treat) + e_{it}\n$$\n\nWhere $\\delta_i$ was the equivalent to $\\delta_1$, and $\\delta_2$ the equivalent for $\\delta_t$.\n\nWhat many didn't know at the time is that @eq-1 would provide correct identification of the Average treatment effect $\\gamma$, under strict assumptions:\n\n- There is no treatment timing heterogeneity (All units are treated at the same time)\n- If there is timing heterogeneity, the treatment effect is homogenous across time and across groups. ($\\gamma$ is the same across time or across groups)\n\nThis assumptions almost never hold. For example, the original treatment may become less effective few periods after they are implemented, and units treated later may experience stronger treatment effects than those treated earlier. When this happen, @eq-1 will provide incorrect results for three related reasons:\n\n1. Linear regressions do not discriminate between good or bad controls when identifying coefficients. They simply exploit all possible varation in the data. \n2. Already treated units would be implicitly used as \"control units\", when analyzing units treated at a later point in time.\n3. Because of this, some treated units will receive \"negative\" weights, when estimating Average treatemnt effects.\n\nOne of the most interesting consequences of this problem is that one may estimate negative treatment effects, even if all units in the sample had a theoreticaly possitive treatment effect.\n\nMany paper published in 2021 including @goodman_bacon_2021, @callaway_santanna_2021, @sun_estimating_2021, @wooldridge_twoway_2021 and @borusyak_revisiting_2022, to name a few, identified this problem, and proposed similar solutions: Estimate ATTs allowing for cohort and timing heterogeneity, avoiding the use of already treated units as controls. \n\nWhile these papers also provide their own estimators (in `Stata`, `R`, and in some cases `python`), I will focus only on two solutions. The ones proposed by @callaway_santanna_2021 and @wooldridge_twoway_2021, which I programmed in `Stata` using `csdid[2]`, and `jwdid`. Both approaches suggest to estimate heterogenous treatment effects based on when a unit is treated (its cohort $G$), and at what point in time one is interested in estimating that effect $T$. We will call them the $ATT(G,T)$. ^[I will not provide details of the model specification in this post, but leave it for some future page on this site.]\n\n##  GxT DID (instead  of 2x2 DID)\n\n### Panel Data\n\nLets assume you have access to Balanced Panel Data. In other words, you observe the same group of individuals across the same window of time. Different individuals are treated at different points in time, and some are not treated at all (never treated). This is the best case scenario, since you do not need to worry about identifying cohorts by treat timing. \n\nLet's see how to estimate this type of models using `csdid` and `jwdid`. They estimate the treatment effects using different strategies, but under specific cases, they will provide the same point estimates. To show how this is done, I will employ the toy-dataset used in @callaway_santanna_2021.\n\nFirst let's set things up, loading the data:\n\n::: {.cell execution_count=1}\n``` {.stata .cell-code}\n** to get the data from my repository\nssc install frause\nfrause mpdta, clear\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nchecking frause consistency and verifying not already installed...\nall files already exist and are up to date.\n(Written by R.              )\n```\n:::\n:::\n\n\nThis dataset contains information at the county level on population size (lpop), employment (lemp), and a variable that indicates when a county instuted a change in minimum wage (first_treat). To estimate a DID model with heterogenous treatment effects, could use either `jwdid` or `csdid`, which are available from SSC.^[If you want to use `csdid2`, please check the blog-post on using \"own installer\", and try `fra install csdid2`.]\n\n::: {.cell execution_count=2}\n``` {.stata .cell-code}\n** This is a dependency for csdid\nssc install drdid, replace\nssc install csdid, replace\nssc install jwdid, replace\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nchecking drdid consistency and verifying not already installed...\nall files already exist and are up to date.\nchecking csdid consistency and verifying not already installed...\nall files already exist and are up to date.\nchecking jwdid consistency and verifying not already installed...\n\nthe following files will be replaced:\n    c:\\ado\\plus\\j\\jwdid.ado\n    c:\\ado\\plus\\j\\jwdid_estat.ado\n\ninstalling into c:\\ado\\plus\\...\ninstallation complete.\n```\n:::\n:::\n\n\nJust one more step (not required but important if you did not identified the `cohort` variable). Lets create a dummy that takes the value of 1 only after the treated unit is treated:\n\n::: {.cell execution_count=3}\n``` {.stata .cell-code}\ngen trt = (first_treat<=year)*(first_treat>0)\n```\n:::\n\n\nThis is what @eq-1 is using. So how do I create the \"*treatment cohort*\" variable?. That can be easily done using one of `csdid` subprograms. You just need to provide the group or panel identifier, and the time variable:\n\n::: {.cell execution_count=4}\n``` {.stata .cell-code}\negen gvar = csgvar(trt), ivar(countyreal) tvar(year)\n```\n:::\n\n\nIts worth noting that the official commands `xthdidregress` and `hdidregress` do not require you to do this, because it automatically creates the gvar internally, based on the information provided. You can now create a small tabulation, as a sanity check, to verity the variable `gvar` is correctly created:\n\n```stata\ntab year gvar\n```\n\n|year\\gvar |         0    |   2004   |    2006   |    2007 |     Total|\n|-----------|--------------|----------|-----------|---------|----------|\n|      2003 |       309    |     20   |      40   |     131 |       500 |\n|      2004 |       309    |     20   |      40   |     131 |       500 |\n|      2005 |       309    |     20   |      40   |     131 |       500 |\n|      2006 |       309    |     20   |      40   |     131 |       500 |\n|      2007 |       309    |     20   |      40   |     131 |       500 |\n|     Total |     1,545    |    100   |     200   |     655 |     2,500 |\n\n\nIf all goes as expected, you a tabulation similar to the one you see here. You have a total of 2500 observations, but only 500 counties. 309 were not treated (had no changes in minimum wage between 2003 and 2007), 20 were treated in 2004, 40 in 2006 and 131 in 2007.\n\nThese numbers are what I call \"effective sample size\", because  `csdid` (and implicitly `jwdid`) use only this ammount of information when estimating the treatment effects. In other words, we should assume the sample size is 20 (for the purposes of model specification and controls).\n\nBy default, `jwdid` uses the not yet treated as comparison group. So, to make the results comparable to `csdid`, I will request using those \"never-treated\" as comparison group. For `csdid`, the default is using short gaps for pre-treatment ATT's, along with the never treated as comaprison group. To change that I will use `long2` option. This will make the following comparable to the outcomes from standard Event-studies estimations. The next lines should produce identical point estimates, with very similar standard errors. \n\n::: {.panel-tabset}\n\n## CSDID\n\n::: {.cell execution_count=5}\n``` {.stata .cell-code}\ncsdid lemp , ivar(county) time(year) gvar(gvar) long2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n............\nDifference-in-difference with Multiple Time Periods\n\n                                                         Number of obs = 2,500\nOutcome model  : regression adjustment\nTreatment model: none\n------------------------------------------------------------------------------\n             | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\ng2004        |\n t_2003_2004 |  -.0105032    .023251    -0.45   0.651    -.0560744    .0350679\n t_2003_2005 |  -.0704232   .0309848    -2.27   0.023    -.1311522   -.0096941\n t_2003_2006 |  -.1372587   .0364357    -3.77   0.000    -.2086713   -.0658461\n t_2003_2007 |  -.1008114   .0343592    -2.93   0.003    -.1681542   -.0334685\n-------------+----------------------------------------------------------------\ng2006        |\n t_2003_2005 |  -.0037693    .031342    -0.12   0.904    -.0651985      .05766\n t_2004_2005 |   .0027508   .0195586     0.14   0.888    -.0355833    .0410849\n t_2005_2006 |  -.0045946   .0177552    -0.26   0.796    -.0393942    .0302049\n t_2005_2007 |  -.0412245   .0202292    -2.04   0.042    -.0808729    -.001576\n-------------+----------------------------------------------------------------\ng2007        |\n t_2003_2006 |   .0033064   .0244519     0.14   0.892    -.0446184    .0512311\n t_2004_2006 |    .033813   .0211292     1.60   0.110    -.0075994    .0752254\n t_2005_2006 |   .0310871   .0178775     1.74   0.082    -.0039522    .0661264\n t_2006_2007 |  -.0260544   .0166554    -1.56   0.118    -.0586985    .0065896\n------------------------------------------------------------------------------\nControl: Never Treated\n\nSee Callaway and Sant'Anna (2021) for details\n```\n:::\n:::\n\n\n## JWDID\n\n::: {.cell execution_count=6}\n``` {.stata .cell-code}\njwdid lemp , ivar(county) time(year) gvar(gvar) never\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWARNING: Singleton observations not dropped; statistical significance is biased\n>  (link)\n(MWFE estimator converged in 2 iterations)\n\nHDFE Linear regression                            Number of obs   =      2,500\nAbsorbing 2 HDFE groups                           F(  12,    499) =       2.88\nStatistics robust to heteroskedasticity           Prob > F        =     0.0008\n                                                  R-squared       =     0.9933\n                                                  Adj R-squared   =     0.9915\n                                                  Within R-sq.    =     0.0124\nNumber of clusters (countyreal) =        500      Root MSE        =     0.1389\n\n                           (Std. err. adjusted for 500 clusters in countyreal)\n------------------------------------------------------------------------------\n             |               Robust\n        lemp | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n   gvar#year#|\n    c.__tr__ |\n  2004 2004  |  -.0105032   .0233492    -0.45   0.653    -.0563781    .0353716\n  2004 2005  |  -.0704232   .0311156    -2.26   0.024    -.1315568   -.0092895\n  2004 2006  |  -.1372587   .0365895    -3.75   0.000    -.2091472   -.0653703\n  2004 2007  |  -.1008114   .0345043    -2.92   0.004    -.1686029   -.0330198\n  2006 2003  |  -.0037693   .0314743    -0.12   0.905    -.0656078    .0580693\n  2006 2004  |   .0027508   .0196411     0.14   0.889    -.0358387    .0413403\n  2006 2006  |  -.0045946   .0178301    -0.26   0.797     -.039626    .0304368\n  2006 2007  |  -.0412245   .0203146    -2.03   0.043    -.0811371   -.0013118\n  2007 2003  |   .0033064   .0245551     0.13   0.893    -.0449378    .0515505\n  2007 2004  |    .033813   .0212184     1.59   0.112    -.0078753    .0755014\n  2007 2005  |   .0310871    .017953     1.73   0.084    -.0041856    .0663599\n  2007 2007  |  -.0260544   .0167257    -1.56   0.120     -.058916    .0068072\n             |\n       _cons |   5.773609   .0033784  1708.97   0.000     5.766971    5.780247\n------------------------------------------------------------------------------\n\nAbsorbed degrees of freedom:\n-----------------------------------------------------+\n Absorbed FE | Categories  - Redundant  = Num. Coefs |\n-------------+---------------------------------------|\n  countyreal |       500         500           0    *|\n        year |         5           0           5     |\n-----------------------------------------------------+\n* = FE nested within cluster; treated as redundant for DoF computation\n```\n:::\n:::\n\n\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}