<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DID: Panel Data &amp; Repeated Crossection – Playing With Stata</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../app_metrics/app_metrics9.html" rel="next">
<link href="../app_metrics/app_metrics7.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-96a2ba0a03145c2fe028468729cb7c1f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-GNMLZDYJ2P"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-GNMLZDYJ2P', { 'anonymize_ip': true});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Playing With Stata</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">my CV and Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../software.html"> 
<span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../stataviz/index.html"> 
<span class="menu-text">Stata Viz</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../stata_do/index.html"> 
<span class="menu-text">Stata Do’s Ado’s</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../app_metrics/index.html"> 
<span class="menu-text">Applied econometrics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chatgpt.html"> 
<span class="menu-text">Odds and Ends</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">about</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../app_metrics/app_metrics1.html">App Metrics</a></li><li class="breadcrumb-item"><a href="../app_metrics/app_metrics8.html">DID: Panel Data &amp; Repeated Crossection</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../WeeMee.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Applied Econometrics</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">App Metrics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Constructing synthetic Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonlinear DID</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong><code>jwdid</code></strong>: A Stata command for the estimation of Difference-in-Differences models using ETWFE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Avg Treatment Effect Heterogeneity in Stata: Basic Commands vs.&nbsp;New CATE Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DRDID/CSDID in Stata</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DID: The Fall</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DID: The Revolution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2x2 DID: Sant’Anna and Zhao (2020)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Making better use of interval-censored data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regressions, OLS and Standard Errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">DID: Panel Data &amp; Repeated Crossection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../app_metrics/app_metrics9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quantile regressions with multiple fixed effects</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#first-things-first" id="toc-first-things-first" class="nav-link active" data-scroll-target="#first-things-first">First Things First</a>
  <ul class="collapse">
  <li><a href="#did-with-multiple-periods-and-time-heterogeneity" id="toc-did-with-multiple-periods-and-time-heterogeneity" class="nav-link" data-scroll-target="#did-with-multiple-periods-and-time-heterogeneity">DID with Multiple Periods and Time Heterogeneity</a></li>
  </ul></li>
  <li><a href="#gxt-did-instead-of-2x2-did" id="toc-gxt-did-instead-of-2x2-did" class="nav-link" data-scroll-target="#gxt-did-instead-of-2x2-did">GxT DID (instead of 2x2 DID)</a>
  <ul class="collapse">
  <li><a href="#panel-data" id="toc-panel-data" class="nav-link" data-scroll-target="#panel-data">Panel Data</a></li>
  </ul></li>
  <li><a href="#repeated-crossection" id="toc-repeated-crossection" class="nav-link" data-scroll-target="#repeated-crossection">Repeated Crossection</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../app_metrics/app_metrics1.html">App Metrics</a></li><li class="breadcrumb-item"><a href="../app_metrics/app_metrics8.html">DID: Panel Data &amp; Repeated Crossection</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DID: Panel Data &amp; Repeated Crossection</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Using <code>CSDID</code> and <code>JWDID</code></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="first-things-first" class="level2">
<h2 class="anchored" data-anchor-id="first-things-first">First Things First</h2>
<section id="did-with-multiple-periods-and-time-heterogeneity" class="level3">
<h3 class="anchored" data-anchor-id="did-with-multiple-periods-and-time-heterogeneity">DID with Multiple Periods and Time Heterogeneity</h3>
<p>If you are reading this, you probably know quite well all the problems associated with the infamous TWFE-DID especification. Nevertheless, its worth a quick recap, in case you are not aware of.</p>
<p>Before the new literature on DID, whenever people wanted to analyze treatment effects using a difference in differences approach, and had access to data with many periods and many individuals, they would tend to use a model specification that look like this:</p>
<p><span id="eq-1"><span class="math display">\[y_{it} = \delta_i + \delta_t + \gamma \times trt + e_{it}
\tag{1}\]</span></span></p>
<p>Where <span class="math inline">\(trt\)</span> was a dummy variable that would take the value of 1 for treated units after the treatment was implemented, and zero otherwise. The idea was that all units with <span class="math inline">\(trt=0\)</span> (those not yet treated) would be used used as controls. In this specification, one is also controlling for time fixed effects <span class="math inline">\(\delta_t\)</span> as well as individual (or group) fixed effects <span class="math inline">\(\delta_i\)</span>.</p>
<p>This specification was considered a generalization of the simple 2x2 DID design:</p>
<p><span class="math display">\[
y = \delta_0 + \delta_1 post+ \delta_2 treat + \gamma \ (post\times treat) + e_{it}
\]</span></p>
<p>Where <span class="math inline">\(\delta_i\)</span> was the equivalent to <span class="math inline">\(\delta_1\)</span>, and <span class="math inline">\(\delta_2\)</span> the equivalent for <span class="math inline">\(\delta_t\)</span>.</p>
<p>What many didn’t know at the time is that <a href="#eq-1" class="quarto-xref">Equation&nbsp;1</a> would provide correct identification of the Average treatment effect <span class="math inline">\(\gamma\)</span>, under strict assumptions:</p>
<ul>
<li>There is no treatment timing heterogeneity (All units are treated at the same time)</li>
<li>If there is timing heterogeneity, the treatment effect is homogenous across time and across groups. (<span class="math inline">\(\gamma\)</span> is the same across time or across groups)</li>
</ul>
<p>This assumptions almost never hold. For example, the original treatment may become less effective few periods after they are implemented, and units treated later may experience stronger treatment effects than those treated earlier. When this happen, <a href="#eq-1" class="quarto-xref">Equation&nbsp;1</a> will provide incorrect results for three related reasons:</p>
<ol type="1">
<li>Linear regressions do not discriminate between good or bad controls when identifying coefficients. They simply exploit all possible varation in the data.</li>
<li>Already treated units would be implicitly used as “control units”, when analyzing units treated at a later point in time.</li>
<li>Because of this, some treated units will receive “negative” weights, when estimating Average treatemnt effects.</li>
</ol>
<p>One of the most interesting consequences of this problem is that one may estimate negative treatment effects, even if all units in the sample had a theoreticaly possitive treatment effect.</p>
<p>Many paper published in 2021 including <span class="citation" data-cites="goodman_bacon_2021">Goodman-Bacon (<a href="#ref-goodman_bacon_2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="callaway_santanna_2021">Callaway and Sant’Anna (<a href="#ref-callaway_santanna_2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="sun_estimating_2021">Sun and Abraham (<a href="#ref-sun_estimating_2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="wooldridge_twoway_2021">Wooldridge (<a href="#ref-wooldridge_twoway_2021" role="doc-biblioref">2021</a>)</span> and <span class="citation" data-cites="borusyak_revisiting_2022">Borusyak, Jaravel, and Spiess (<a href="#ref-borusyak_revisiting_2022" role="doc-biblioref">2022</a>)</span>, to name a few, identified this problem, and proposed similar solutions: Estimate ATTs allowing for cohort and timing heterogeneity, avoiding the use of already treated units as controls.</p>
<p>While these papers also provide their own estimators (in <code>Stata</code>, <code>R</code>, and in some cases <code>python</code>), I will focus only on two solutions. The ones proposed by <span class="citation" data-cites="callaway_santanna_2021">Callaway and Sant’Anna (<a href="#ref-callaway_santanna_2021" role="doc-biblioref">2021</a>)</span> and <span class="citation" data-cites="wooldridge_twoway_2021">Wooldridge (<a href="#ref-wooldridge_twoway_2021" role="doc-biblioref">2021</a>)</span>, which I programmed in <code>Stata</code> using <code>csdid[2]</code>, and <code>jwdid</code>. Both approaches suggest to estimate heterogenous treatment effects based on when a unit is treated (its cohort <span class="math inline">\(G\)</span>), and at what point in time one is interested in estimating that effect <span class="math inline">\(T\)</span>. We will call them the <span class="math inline">\(ATT(G,T)\)</span>. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
</section>
<section id="gxt-did-instead-of-2x2-did" class="level2">
<h2 class="anchored" data-anchor-id="gxt-did-instead-of-2x2-did">GxT DID (instead of 2x2 DID)</h2>
<section id="panel-data" class="level3">
<h3 class="anchored" data-anchor-id="panel-data">Panel Data</h3>
<p>Lets assume you have access to Balanced Panel Data. In other words, you observe the same group of individuals across the same window of time. Different individuals are treated at different points in time, and some are not treated at all (never treated). This is the best case scenario, since you do not need to worry about identifying cohorts by treat timing.</p>
<p>Let’s see how to estimate this type of models using <code>csdid</code> and <code>jwdid</code>. They estimate the treatment effects using different strategies, but under specific cases, they will provide the same point estimates. To show how this is done, I will employ the toy-dataset used in <span class="citation" data-cites="callaway_santanna_2021">Callaway and Sant’Anna (<a href="#ref-callaway_santanna_2021" role="doc-biblioref">2021</a>)</span>.</p>
<p>First let’s set things up, loading the data:</p>
<div id="7cc89832" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>** to <span class="fu">get</span> the <span class="kw">data</span> from my repository</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">ssc</span> install frause, <span class="kw">replace</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>frause mpdta, <span class="kw">clear</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This dataset contains information at the county level on population size (lpop), employment (lemp), and a variable that indicates when a county instuted a change in minimum wage (first_treat). To estimate a DID model with heterogenous treatment effects, could use either <code>jwdid</code> or <code>csdid</code>, which are available from SSC.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div id="6f4611a3" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>** This is a dependency <span class="kw">for</span> csdid</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">ssc</span> install drdid, <span class="kw">replace</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">ssc</span> install csdid, <span class="kw">replace</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">ssc</span> install jwdid, <span class="kw">replace</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Just one more step (not required but important if you did not identified the <code>cohort</code> variable). Lets create a dummy that takes the value of 1 only after the treated unit is treated:</p>
<div id="7814786e" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> trt = (first_treat&lt;=<span class="fu">year</span>)*(first_treat&gt;0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This is what <a href="#eq-1" class="quarto-xref">Equation&nbsp;1</a> is using. So how do I create the “<em>treatment cohort</em>” variable?. That can be easily done using one of <code>csdid</code> subprograms. You just need to provide the group or panel identifier, and the time variable:</p>
<div id="4c2c6712" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">egen</span> gvar = csgvar(trt), ivar(countyreal) tvar(<span class="fu">year</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Its worth noting that the official commands <code>xthdidregress</code> and <code>hdidregress</code> do not require you to do this, because it automatically creates the gvar internally, based on the information provided. You can now create a small tabulation, as a sanity check, to verity the variable <code>gvar</code> is correctly created:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">tab</span> <span class="fu">year</span> gvar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>year</th>
<th>0</th>
<th>2004</th>
<th>2006</th>
<th>2007</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2003</td>
<td>309</td>
<td>20</td>
<td>40</td>
<td>131</td>
<td>500</td>
</tr>
<tr class="even">
<td>2004</td>
<td>309</td>
<td>20</td>
<td>40</td>
<td>131</td>
<td>500</td>
</tr>
<tr class="odd">
<td>2005</td>
<td>309</td>
<td>20</td>
<td>40</td>
<td>131</td>
<td>500</td>
</tr>
<tr class="even">
<td>2006</td>
<td>309</td>
<td>20</td>
<td>40</td>
<td>131</td>
<td>500</td>
</tr>
<tr class="odd">
<td>2007</td>
<td>309</td>
<td>20</td>
<td>40</td>
<td>131</td>
<td>500</td>
</tr>
<tr class="even">
<td>Total</td>
<td>1,545</td>
<td>100</td>
<td>200</td>
<td>655</td>
<td>2,500</td>
</tr>
</tbody>
</table>
<p>If all goes as expected, you a tabulation similar to the one you see here. You have a total of 2500 observations, but only 500 counties. 309 were not treated (had no changes in minimum wage between 2003 and 2007), 20 were treated in 2004, 40 in 2006 and 131 in 2007.</p>
<p>These numbers are what I call “effective sample size”, because <code>csdid</code> (and implicitly <code>jwdid</code>) use only this ammount of information when estimating the treatment effects. In other words, we should assume the sample size is 20 (for the purposes of model specification and controls).</p>
<p>By default, <code>jwdid</code> uses the not yet treated as comparison group. So, to make the results comparable to <code>csdid</code>, I will request using those “never-treated” as comparison group. For <code>csdid</code>, the default is using short gaps for pre-treatment ATT’s, along with the never treated as comaprison group. To change that I will use <code>long2</code> option. This will make the following comparable to the outcomes from standard Event-studies estimations. The next lines should produce identical point estimates, with very similar standard errors.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">CSDID</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">JWDID</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="143260ef" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>csdid lemp , ivar(county) time(<span class="fu">year</span>) gvar(gvar) long2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>............
Difference-in-difference with Multiple Time Periods

                                                         Number of obs = 2,500
Outcome model  : regression adjustment
Treatment model: none
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
g2004        |
 t_2003_2004 |  -.0105032    .023251    -0.45   0.651    -.0560744    .0350679
 t_2003_2005 |  -.0704232   .0309848    -2.27   0.023    -.1311522   -.0096941
 t_2003_2006 |  -.1372587   .0364357    -3.77   0.000    -.2086713   -.0658461
 t_2003_2007 |  -.1008114   .0343592    -2.93   0.003    -.1681542   -.0334685
-------------+----------------------------------------------------------------
g2006        |
 t_2003_2005 |  -.0037693    .031342    -0.12   0.904    -.0651985      .05766
 t_2004_2005 |   .0027508   .0195586     0.14   0.888    -.0355833    .0410849
 t_2005_2006 |  -.0045946   .0177552    -0.26   0.796    -.0393942    .0302049
 t_2005_2007 |  -.0412245   .0202292    -2.04   0.042    -.0808729    -.001576
-------------+----------------------------------------------------------------
g2007        |
 t_2003_2006 |   .0033064   .0244519     0.14   0.892    -.0446184    .0512311
 t_2004_2006 |    .033813   .0211292     1.60   0.110    -.0075994    .0752254
 t_2005_2006 |   .0310871   .0178775     1.74   0.082    -.0039522    .0661264
 t_2006_2007 |  -.0260544   .0166554    -1.56   0.118    -.0586985    .0065896
------------------------------------------------------------------------------
Control: Never Treated

See Callaway and Sant'Anna (2021) for details</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="05961dff" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>jwdid lemp , ivar(county) time(<span class="fu">year</span>) gvar(gvar) never</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING: Singleton observations not dropped; statistical significance is biased
&gt;  (link)
(MWFE estimator converged in 2 iterations)

HDFE Linear regression                            Number of obs   =      2,500
Absorbing 2 HDFE groups                           F(  12,    499) =       2.88
Statistics robust to heteroskedasticity           Prob &gt; F        =     0.0008
                                                  R-squared       =     0.9933
                                                  Adj R-squared   =     0.9915
                                                  Within R-sq.    =     0.0124
Number of clusters (countyreal) =        500      Root MSE        =     0.1389

                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |               Robust
        lemp | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
   gvar#year#|
    c.__tr__ |
  2004 2004  |  -.0105032   .0233492    -0.45   0.653    -.0563781    .0353716
  2004 2005  |  -.0704232   .0311156    -2.26   0.024    -.1315568   -.0092895
  2004 2006  |  -.1372587   .0365895    -3.75   0.000    -.2091472   -.0653703
  2004 2007  |  -.1008114   .0345043    -2.92   0.004    -.1686029   -.0330198
  2006 2003  |  -.0037693   .0314743    -0.12   0.905    -.0656078    .0580693
  2006 2004  |   .0027508   .0196411     0.14   0.889    -.0358387    .0413403
  2006 2006  |  -.0045946   .0178301    -0.26   0.797     -.039626    .0304368
  2006 2007  |  -.0412245   .0203146    -2.03   0.043    -.0811371   -.0013118
  2007 2003  |   .0033064   .0245551     0.13   0.893    -.0449378    .0515505
  2007 2004  |    .033813   .0212184     1.59   0.112    -.0078753    .0755014
  2007 2005  |   .0310871    .017953     1.73   0.084    -.0041856    .0663599
  2007 2007  |  -.0260544   .0167257    -1.56   0.120     -.058916    .0068072
             |
       _cons |   5.773609   .0033784  1708.97   0.000     5.766971    5.780247
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
  countyreal |       500         500           0    *|
        year |         5           0           5     |
-----------------------------------------------------+
* = FE nested within cluster; treated as redundant for DoF computation</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>You can of course add controls. In this case <code>lpop</code> is a time constant variable, so it can be added to both commands. For us to obtain the same results, however, you need to add the <code>method(reg)</code> to <code>csdid</code>. Otherwise it will implement the double robust estimator <code>dripw</code> (default)</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">CSDID</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">JWDID</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div id="1e77b80d" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>csdid lemp lpop , ivar(county) time(<span class="fu">year</span>) gvar(gvar) long2 method(<span class="kw">reg</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>............
Difference-in-difference with Multiple Time Periods

                                                         Number of obs = 2,500
Outcome model  : regression adjustment
Treatment model: none
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
g2004        |
 t_2003_2004 |  -.0149112   .0220557    -0.68   0.499    -.0581396    .0283171
 t_2003_2005 |  -.0769963   .0283597    -2.71   0.007    -.1325804   -.0214122
 t_2003_2006 |  -.1410801   .0348363    -4.05   0.000     -.209358   -.0728022
 t_2003_2007 |  -.1075443   .0327377    -3.29   0.001     -.171709   -.0433796
-------------+----------------------------------------------------------------
g2006        |
 t_2003_2005 |   .0090343   .0300861     0.30   0.764    -.0499333     .068002
 t_2004_2005 |   .0069683   .0183458     0.38   0.704    -.0289888    .0429254
 t_2005_2006 |   .0007655   .0191959     0.04   0.968    -.0368578    .0383888
 t_2005_2007 |  -.0415356   .0197169    -2.11   0.035      -.08018   -.0028913
-------------+----------------------------------------------------------------
g2007        |
 t_2003_2006 |   .0068961   .0244888     0.28   0.778    -.0411011    .0548933
 t_2004_2006 |   .0332619   .0211607     1.57   0.116    -.0082123    .0747362
 t_2005_2006 |   .0285021   .0181321     1.57   0.116    -.0070361    .0640403
 t_2006_2007 |  -.0287895   .0161679    -1.78   0.075    -.0604779    .0028989
------------------------------------------------------------------------------
Control: Never Treated

See Callaway and Sant'Anna (2021) for details</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div id="c7f0438a" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>jwdid lemp lpop, ivar(county) time(<span class="fu">year</span>) gvar(gvar) never </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING: Singleton observations not dropped; statistical significance is biased
&gt;  (link)
(MWFE estimator converged in 2 iterations)
note: 2007.year#c.lpop omitted because of collinearity

HDFE Linear regression                            Number of obs   =      2,500
Absorbing 2 HDFE groups                           F(  28,    499) =       3.15
Statistics robust to heteroskedasticity           Prob &gt; F        =     0.0000
                                                  R-squared       =     0.9934
                                                  Adj R-squared   =     0.9916
                                                  Within R-sq.    =     0.0240
Number of clusters (countyreal) =        500      Root MSE        =     0.1386

                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |               Robust
        lemp | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
   gvar#year#|
    c.__tr__ |
  2004 2004  |  -.0149112   .0222198    -0.67   0.502    -.0585672    .0287448
  2004 2005  |  -.0769963   .0277681    -2.77   0.006    -.1315531   -.0224395
  2004 2006  |  -.1410801   .0322433    -4.38   0.000    -.2044295   -.0777307
  2004 2007  |  -.1075443   .0328764    -3.27   0.001    -.1721375    -.042951
  2006 2003  |   .0090343   .0302224     0.30   0.765    -.0503444    .0684131
  2006 2004  |   .0069683   .0181921     0.38   0.702    -.0287742    .0427108
  2006 2006  |   .0007655   .0186329     0.04   0.967    -.0358432    .0373742
  2006 2007  |  -.0415356   .0191982    -2.16   0.031    -.0792549   -.0038164
  2007 2003  |   .0068961   .0246543     0.28   0.780    -.0415429    .0553351
  2007 2004  |   .0332619   .0213008     1.56   0.119    -.0085883    .0751122
  2007 2005  |   .0285021   .0182653     1.56   0.119    -.0073843    .0643885
  2007 2007  |  -.0287895   .0161312    -1.78   0.075     -.060483     .002904
             |
   gvar#year#|
    c.__tr__#|
   c._x_lpop |
  2004 2004  |   .0005953   .0183556     0.03   0.974    -.0354686    .0366592
  2004 2005  |   .0234096   .0183749     1.27   0.203     -.012692    .0595113
  2004 2006  |   .0482261   .0224194     2.15   0.032      .004178    .0922742
  2004 2007  |   .0091886   .0271423     0.34   0.735    -.0441386    .0625158
  2006 2003  |  -.0126074   .0243335    -0.52   0.605    -.0604162    .0352014
  2006 2004  |  -.0177865   .0161892    -1.10   0.272    -.0495939    .0140208
  2006 2006  |   .0282074   .0141213     2.00   0.046     .0004628     .055952
  2006 2007  |   .0277793   .0180844     1.54   0.125    -.0077516    .0633102
  2007 2003  |   .0083787   .0254037     0.33   0.742    -.0415327    .0582902
  2007 2004  |  -.0079105   .0188673    -0.42   0.675    -.0449797    .0291587
  2007 2005  |  -.0025825   .0178299    -0.14   0.885    -.0376135    .0324484
  2007 2007  |  -.0203637   .0162117    -1.26   0.210    -.0522153    .0114878
             |
 year#c.lpop |
       2003  |  -.0229821   .0129329    -1.78   0.076    -.0483918    .0024277
       2004  |  -.0079359   .0107757    -0.74   0.462    -.0291072    .0132355
       2005  |  -.0005453   .0097177    -0.06   0.955     -.019638    .0185474
       2006  |  -.0099382   .0090048    -1.10   0.270    -.0276302    .0077537
       2007  |          0  (omitted)
             |
       _cons |   5.800979   .0225656   257.07   0.000     5.756644    5.845315
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
  countyreal |       500         500           0    *|
        year |         5           0           5     |
-----------------------------------------------------+
* = FE nested within cluster; treated as redundant for DoF computation</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>In general, however, you may not be interested in analyzing each individual ATTGT, but rather some aggregated results. For example, overall average, or dynamic effects.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Prof.&nbsp;Wooldrige, however, also suggest to ajust standard errors to account for sampling variation on the covariates. To do so, I need to modify the syntax of <code>jwdid</code> slighly, as well as the post-estimation commands.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">CSDID</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">JWDID</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false">JWDID: vce(unconditional)</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div id="a910ddb2" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span>:csdid lemp lpop , ivar(county) time(<span class="fu">year</span>) gvar(gvar) long2 method(<span class="kw">reg</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> simple</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> event</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> calendar</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> <span class="fu">group</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Average Treatment Effect on Treated
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         ATT |  -.0419686   .0114448    -3.67   0.000    -.0644001   -.0195372
------------------------------------------------------------------------------
ATT by Periods Before and After treatment
Event Study:Dynamic effects
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
     Pre_avg |   .0193186   .0171138     1.13   0.259    -.0142239     .052861
    Post_avg |  -.0807817   .0187459    -4.31   0.000    -.1175229   -.0440405
         Tm4 |   .0068961   .0244888     0.28   0.778    -.0411011    .0548933
         Tm3 |   .0275947   .0180257     1.53   0.126    -.0077351    .0629244
         Tm2 |    .023465   .0144416     1.62   0.104    -.0048402    .0517701
         Tp0 |  -.0211467    .011481    -1.84   0.065    -.0436492    .0013557
         Tp1 |  -.0533559   .0162931    -3.27   0.001    -.0852897    -.021422
         Tp2 |  -.1410801   .0348363    -4.05   0.000     -.209358   -.0728022
         Tp3 |  -.1075443   .0327377    -3.29   0.001     -.171709   -.0433796
------------------------------------------------------------------------------
ATT by Calendar Period
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    CAverage |  -.0445323    .014885    -2.99   0.003    -.0737064   -.0153582
       T2004 |  -.0149112   .0220557    -0.68   0.499    -.0581396    .0283171
       T2005 |  -.0769963   .0283597    -2.71   0.007    -.1325804   -.0214122
       T2006 |  -.0465164   .0209984    -2.22   0.027    -.0876724   -.0053603
       T2007 |  -.0397054   .0128659    -3.09   0.002     -.064922   -.0144888
------------------------------------------------------------------------------
ATT by group
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
    GAverage |  -.0329292   .0117872    -2.79   0.005    -.0560318   -.0098267
       G2004 |   -.085133   .0242512    -3.51   0.000    -.1326645   -.0376015
       G2006 |  -.0203851   .0174025    -1.17   0.241    -.0544933    .0137232
       G2007 |  -.0287895   .0161679    -1.78   0.075    -.0604779    .0028989
------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div id="bceeae98" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span>:jwdid lemp lpop, ivar(county) time(<span class="fu">year</span>) gvar(gvar) never </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> simple</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> event</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> calendar</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> <span class="fu">group</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING: Singleton observations not dropped; statistical significance is biased
&gt;  (link)
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |  -.0419686   .0109096    -3.85   0.000     -.063351   -.0205863
------------------------------------------------------------------------------
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
   __event__ |
(2 vs 1) -4  |   .0068961   .0246543     0.28   0.780    -.0414254    .0552177
(2 vs 1) -3  |   .0275947   .0181227     1.52   0.128    -.0079251    .0631145
(2 vs 1) -2  |    .023465   .0145109     1.62   0.106    -.0049758    .0519057
(2 vs 1) -1  |          0  (omitted)
 (2 vs 1) 0  |  -.0211467   .0113774    -1.86   0.063     -.043446    .0011525
 (2 vs 1) 1  |  -.0533559    .015752    -3.39   0.001    -.0842293   -.0224824
 (2 vs 1) 2  |  -.1410801   .0322433    -4.38   0.000    -.2042759   -.0778843
 (2 vs 1) 3  |  -.1075443   .0328764    -3.27   0.001    -.1719809   -.0431077
------------------------------------------------------------------------------
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
__calendar__ |
   (2 vs 1)  |
       2004  |  -.0149112   .0222198    -0.67   0.502    -.0584613    .0286389
   (2 vs 1)  |
       2005  |  -.0769963   .0277681    -2.77   0.006    -.1314208   -.0225719
   (2 vs 1)  |
       2006  |  -.0465164   .0184021    -2.53   0.011    -.0825839   -.0104488
   (2 vs 1)  |
       2007  |  -.0397054   .0127042    -3.13   0.002    -.0646051   -.0148057
------------------------------------------------------------------------------
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
   __group__ |
   (2 vs 1)  |
       2004  |   -.085133   .0237216    -3.59   0.000    -.1316265   -.0386395
   (2 vs 1)  |
       2006  |  -.0203851   .0167622    -1.22   0.224    -.0532384    .0124683
   (2 vs 1)  |
       2007  |  -.0287895   .0161312    -1.78   0.074    -.0604061    .0028271
------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div id="c2101755" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span>:jwdid lemp lpop, ivar(county) time(<span class="fu">year</span>) gvar(gvar) never <span class="co">///</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    method(<span class="kw">regress</span>) <span class="fu">group</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> simple, <span class="kw">vce</span>(unconditional)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> event, <span class="kw">vce</span>(unconditional)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> calendar, <span class="kw">vce</span>(unconditional)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="kw">estat</span> <span class="fu">group</span>, <span class="kw">vce</span>(unconditional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |            Unconditional
             | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |  -.0419686   .0115467    -3.63   0.000    -.0646548   -.0192824
------------------------------------------------------------------------------
                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |            Unconditional
             | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
   __event__ |
(2 vs 1) -4  |   .0068961   .0247069     0.28   0.780    -.0416463    .0554385
(2 vs 1) -3  |   .0275947   .0181862     1.52   0.130    -.0081364    .0633257
(2 vs 1) -2  |    .023465   .0145703     1.61   0.108    -.0051617    .0520916
(2 vs 1) -1  |          0  (omitted)
 (2 vs 1) 0  |  -.0211467   .0115833    -1.83   0.069    -.0439048    .0016113
 (2 vs 1) 1  |  -.0533559   .0164382    -3.25   0.001    -.0856524   -.0210593
 (2 vs 1) 2  |  -.1410801   .0351465    -4.01   0.000    -.2101335   -.0720267
 (2 vs 1) 3  |  -.1075443   .0330292    -3.26   0.001    -.1724378   -.0426508
------------------------------------------------------------------------------
                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |            Unconditional
             | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
__calendar__ |
   (2 vs 1)  |
       2004  |  -.0149112   .0222521    -0.67   0.503    -.0586306    .0288081
   (2 vs 1)  |
       2005  |  -.0769963   .0286123    -2.69   0.007    -.1332117   -.0207809
   (2 vs 1)  |
       2006  |  -.0465164   .0211854    -2.20   0.029    -.0881399   -.0048928
   (2 vs 1)  |
       2007  |  -.0397054   .0129804    -3.06   0.002    -.0652084   -.0142024
------------------------------------------------------------------------------
                           (Std. err. adjusted for 500 clusters in countyreal)
------------------------------------------------------------------------------
             |            Unconditional
             | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at@|
   __group__ |
   (2 vs 1)  |
       2004  |   -.085133   .0244672    -3.48   0.001    -.1332044   -.0370616
   (2 vs 1)  |
       2006  |  -.0203851   .0175575    -1.16   0.246    -.0548807    .0141106
   (2 vs 1)  |
       2007  |  -.0287895   .0163118    -1.76   0.078    -.0608378    .0032589
------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Again, both showing identical point estimates with slighly different standard errors.</p>
</section>
</section>
<section id="repeated-crossection" class="level2">
<h2 class="anchored" data-anchor-id="repeated-crossection">Repeated Crossection</h2>
<p>Repeated crossection operates slighly different than panel data. On the one hand, you do not observe the same units across time. Thus, there is no <em>unit specific fixed-effect</em>. Instead one would be trying to account for cohort specific effect, or treatment-level fixed effects. This may become clearer with an example.</p>
<p>Lets us first consider the same dataset as before. To simulate the situation of repeated crossection, lets assume that each round, data was collected for a random sample of counties within each State, and that, for some unknown reason, we cannot identify counties across time. Lets us also assume that the treatment was implemented at the State level (for clustering purposes). First some data preparation.</p>
<p>To simulate repeated crossection structure, I will drop 10% of the data, create a <strong><em>State id</em></strong>, and drop the county identifier.</p>
<div id="bf29311a" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>** <span class="kw">load</span> and obtain trt</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>frause mpdta, <span class="kw">clear</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> trt = (first_treat&lt;=<span class="fu">year</span>)*(first_treat&gt;0)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> state = <span class="kw">int</span>(countyreal/1000)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>** Randomly <span class="kw">keep</span> 90% <span class="kw">of</span> the <span class="kw">data</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="dv">seed</span> 1</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="kw">sample</span> 90</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="kw">drop</span> countyreal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Written by R.              )
(250 observations deleted)</code></pre>
</div>
</div>
<p>Next is to create the <code>gvar</code>. This will follow the same syntax as before, with the main difference that instead of using <strong>countyreal</strong> as <code>ivar</code>, we will use <code>state</code>. Its important that this variable represents the identifier of the level at which the treatment was implemented, and that we can follow up across time.</p>
<div id="5997f36f" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">egen</span> gvar = csgvar(trt), ivar(state) tvar(<span class="fu">year</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>And as always, its a good idea to crosstabulate year with the new gvar:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">tab</span> <span class="fu">year</span> gvar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>year</th>
<th>0</th>
<th>2004</th>
<th>2006</th>
<th>2007</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2003</td>
<td>279</td>
<td>19</td>
<td>35</td>
<td>114</td>
<td>447</td>
</tr>
<tr class="even">
<td>2004</td>
<td>286</td>
<td>19</td>
<td>34</td>
<td>117</td>
<td>456</td>
</tr>
<tr class="odd">
<td>2005</td>
<td>279</td>
<td>18</td>
<td>38</td>
<td>121</td>
<td>456</td>
</tr>
<tr class="even">
<td>2006</td>
<td>275</td>
<td>18</td>
<td>40</td>
<td>115</td>
<td>448</td>
</tr>
<tr class="odd">
<td>2007</td>
<td>275</td>
<td>18</td>
<td>36</td>
<td>114</td>
<td>443</td>
</tr>
<tr class="even">
<td>Total</td>
<td>1,474</td>
<td>93</td>
<td>193</td>
<td>615</td>
<td>2,375</td>
</tr>
</tbody>
</table>
<p>What you should observe, as shown here, is that you still have roughtly the same number of observations per <code>gvar</code> across time. This is important because you need to have a groups that are comparable across time. Think of this as having a pseudo panel.</p>
<p>In terms of estimation, the syntax needs to be adjusted slighly:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">CSDID</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">JWDID-I</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false">JWDID-II</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>If you are using <code>csdid</code>, the adjustment simply requires to drop <code>ivar</code> option. To make sure we are clustering at the correct level, one should use <code>cluster()</code> instead, using the pseudo panel identifier <code>state</code> as clustering variable:</p>
<div id="71f32a2b" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>csdid lemp , <span class="kw">cluster</span>(state) time(<span class="fu">year</span>) gvar(gvar) long2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>............
Difference-in-difference with Multiple Time Periods

                                                         Number of obs = 2,250
Outcome model  : regression adjustment
Treatment model: none
                                 (Std. err. adjusted for 29 clusters in state)
------------------------------------------------------------------------------
             | Coefficient  Std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
g2004        |
 t_2003_2004 |   .0671177   .0420718     1.60   0.111    -.0153416     .149577
 t_2003_2005 |  -.2982137   .0481335    -6.20   0.000    -.3925536   -.2038737
 t_2003_2006 |  -.2056332   .0352891    -5.83   0.000    -.2747986   -.1364679
 t_2003_2007 |  -.0657414   .0394828    -1.67   0.096    -.1431262    .0116435
-------------+----------------------------------------------------------------
g2006        |
 t_2003_2005 |   .0718644   .0669577     1.07   0.283    -.0593703     .203099
 t_2004_2005 |   .2762365   .1143842     2.41   0.016     .0520476    .5004253
 t_2005_2006 |   .1252212   .0839351     1.49   0.136    -.0392885    .2897309
 t_2005_2007 |   .1471258   .0853201     1.72   0.085    -.0200985    .3143501
-------------+----------------------------------------------------------------
g2007        |
 t_2003_2006 |   .0932773   .0789284     1.18   0.237    -.0614195    .2479742
 t_2004_2006 |    .124871   .0761301     1.64   0.101    -.0243412    .2740832
 t_2005_2006 |  -.0352257   .0628217    -0.56   0.575    -.1583539    .0879025
 t_2006_2007 |  -.0136172   .0952995    -0.14   0.886    -.2004007    .1731663
------------------------------------------------------------------------------
Control: Never Treated

See Callaway and Sant'Anna (2021) for details</code></pre>
</div>
</div>
<p>Aggregations are obtained using <code>estat</code> post estimation commnads.</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p>If you are using <code>jwdid</code>, there are two alternatives. The first one is to use <code>ivar()</code> with the new pseudo panel identifier (<code>state</code>).</p>
<div id="cd0c74bb" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>jwdid lemp , ivar(state) time(<span class="fu">year</span>) gvar(gvar) never</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING: Singleton observations not dropped; statistical significance is biased
&gt;  (link)
(MWFE estimator converged in 4 iterations)
warning: missing F statistic; dropped variables due to collinearity or too few 
&gt; clusters

HDFE Linear regression                            Number of obs   =      2,250
Absorbing 2 HDFE groups                           F(  12,     28) =          .
Statistics robust to heteroskedasticity           Prob &gt; F        =          .
                                                  R-squared       =     0.1797
                                                  Adj R-squared   =     0.1630
                                                  Within R-sq.    =     0.0010
Number of clusters (state)   =         29         Root MSE        =     1.3796

                                 (Std. err. adjusted for 29 clusters in state)
------------------------------------------------------------------------------
             |               Robust
        lemp | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
   gvar#year#|
    c.__tr__ |
  2004 2004  |   .0799107   .0377474     2.12   0.043     .0025886    .1572328
  2004 2005  |  -.2926293   .0448166    -6.53   0.000    -.3844319   -.2008267
  2004 2006  |  -.1982852     .03159    -6.28   0.000    -.2629944   -.1335761
  2004 2007  |  -.0582612   .0431331    -1.35   0.188    -.1466153    .0300929
  2006 2003  |   .0498869    .068996     0.72   0.476    -.0914451    .1912188
  2006 2004  |   .2964946   .1219394     2.43   0.022      .046713    .5462761
  2006 2006  |   .1220182   .0809493     1.51   0.143    -.0437989    .2878353
  2006 2007  |   .1401132   .0801401     1.75   0.091    -.0240464    .3042727
  2007 2003  |   .0118143   .0676839     0.17   0.863      -.12683    .1504585
  2007 2004  |   .0855261   .0903276     0.95   0.352    -.0995017    .2705538
  2007 2005  |  -.0974496   .0709482    -1.37   0.180    -.2427804    .0478812
  2007 2007  |  -.0729594   .0980111    -0.74   0.463    -.2737261    .1278073
             |
       _cons |   5.762268   .0141152   408.23   0.000     5.733355    5.791182
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
       state |        29          29           0    *|
        year |         5           0           5     |
-----------------------------------------------------+
* = FE nested within cluster; treated as redundant for DoF computation</code></pre>
</div>
</div>
<p>Data will be clustered at the state level, explicitly accounting for State fixed effects.</p>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<p>Alternatively, one could change <code>ivar()</code> with <code>cluster()</code>, to ensure clustering is done at the correct level, and add the option <code>group</code>, so that cohort fixed effects are added to the specification.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div id="6ad1df96" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>jwdid lemp , <span class="kw">cluster</span>(state) time(<span class="fu">year</span>) gvar(gvar) never <span class="fu">group</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING: Singleton observations not dropped; statistical significance is biased
&gt;  (link)
(MWFE estimator converged in 3 iterations)
warning: missing F statistic; dropped variables due to collinearity or too few 
&gt; clusters

HDFE Linear regression                            Number of obs   =      2,250
Absorbing 2 HDFE groups                           F(  12,     28) =          .
Statistics robust to heteroskedasticity           Prob &gt; F        =          .
                                                  R-squared       =     0.0298
                                                  Adj R-squared   =     0.0215
                                                  Within R-sq.    =     0.0008
Number of clusters (state)   =         29         Root MSE        =     1.4916

                                 (Std. err. adjusted for 29 clusters in state)
------------------------------------------------------------------------------
             |               Robust
        lemp | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
   gvar#year#|
    c.__tr__ |
  2004 2004  |   .0671177   .0429985     1.56   0.130    -.0209608    .1551962
  2004 2005  |  -.2982137   .0491937    -6.06   0.000    -.3989825   -.1974449
  2004 2006  |  -.2056332   .0360664    -5.70   0.000    -.2795119   -.1317546
  2004 2007  |  -.0657414   .0403525    -1.63   0.114    -.1483996    .0169169
  2006 2003  |   .0718644   .0684326     1.05   0.303    -.0683133    .2120421
  2006 2004  |   .2762365   .1169037     2.36   0.025     .0367701    .5157028
  2006 2006  |   .1252212   .0857839     1.46   0.155    -.0504991    .3009415
  2006 2007  |   .1471258   .0871994     1.69   0.103    -.0314941    .3257457
  2007 2003  |   .0932773    .080667     1.16   0.257    -.0719614    .2585161
  2007 2004  |    .124871    .077807     1.60   0.120    -.0345093    .2842514
  2007 2005  |  -.0352257   .0642054    -0.55   0.588    -.1667446    .0962931
  2007 2007  |  -.0136172   .0973986    -0.14   0.890    -.2131292    .1858948
             |
       _cons |   5.749808   .1159179    49.60   0.000     5.512361    5.987255
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
        gvar |         4           0           4     |
        year |         5           1           4     |
-----------------------------------------------------+</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The results across the different approaches will be different because of how the data is used. But, as you can see here, point estimates are broadly comparable.</p>
<p>As far as I know, either option is correct.</p>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>I hope this reference helps people who want to use <code>jwdid</code> and <code>csdid</code> for the estimation of DID models in the presence of repeated crossection.</p>
<p>If you have comments, or questions, do not hesitate to contact me.</p>


<!-- -->


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-borusyak_revisiting_2022" class="csl-entry" role="listitem">
Borusyak, Kirill, Xavier Jaravel, and Jann Spiess. 2022. <span>“Revisiting <span>Event</span> <span>Study</span> <span>Designs</span>: <span>Robust</span> and <span>Efficient</span> <span>Estimation</span>.”</span> arXiv. <a href="https://doi.org/10.48550/arXiv.2108.12419">https://doi.org/10.48550/arXiv.2108.12419</a>.
</div>
<div id="ref-callaway_santanna_2021" class="csl-entry" role="listitem">
Callaway, Brantly, and Pedro H. C. Sant’Anna. 2021. <span>“Difference-in-<span>Differences</span> with Multiple Time Periods.”</span> <em>Journal of Econometrics</em>, Themed <span>Issue</span>: <span>Treatment</span> <span>Effect</span> 1, 225 (2): 200–230. <a href="https://doi.org/10.1016/j.jeconom.2020.12.001">https://doi.org/10.1016/j.jeconom.2020.12.001</a>.
</div>
<div id="ref-goodman_bacon_2021" class="csl-entry" role="listitem">
Goodman-Bacon, Andrew. 2021. <span>“Difference-in-Differences with Variation in Treatment Timing.”</span> <em>Journal of Econometrics</em>, Themed <span>Issue</span>: <span>Treatment</span> <span>Effect</span> 1, 225 (2): 254–77. <a href="https://doi.org/10.1016/j.jeconom.2021.03.014">https://doi.org/10.1016/j.jeconom.2021.03.014</a>.
</div>
<div id="ref-sun_estimating_2021" class="csl-entry" role="listitem">
Sun, Liyang, and Sarah Abraham. 2021. <span>“Estimating Dynamic Treatment Effects in Event Studies with Heterogeneous Treatment Effects.”</span> <em>Journal of Econometrics</em>, Themed <span>Issue</span>: <span>Treatment</span> <span>Effect</span> 1, 225 (2): 175–99. <a href="https://doi.org/10.1016/j.jeconom.2020.09.006">https://doi.org/10.1016/j.jeconom.2020.09.006</a>.
</div>
<div id="ref-wooldridge_twoway_2021" class="csl-entry" role="listitem">
Wooldridge, Jeffrey M. 2021. <span>“Two-<span>Way</span> <span>Fixed</span> <span>Effects</span>, the <span>Two</span>-<span>Way</span> <span>Mundlak</span> <span>Regression</span>, and <span>Difference</span>-in-<span>Differences</span> <span>Estimators</span>.”</span> {SSRN} {Scholarly} {Paper}. Rochester, NY. <a href="https://doi.org/10.2139/ssrn.3906345">https://doi.org/10.2139/ssrn.3906345</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>I will not provide details of the model specification in this post, but leave it for some future page on this site.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>If you want to use <code>csdid2</code>, please check the blog-post on using “own installer”, and try <code>fra install csdid2</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>also available <code>group</code> and <code>calendar</code><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>In my repository, the newer version of <code>jwdid</code> does this automatically if <code>ivar()</code> is not provided.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/friosavila\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../app_metrics/app_metrics7.html" class="pagination-link" aria-label="Linear Regressions, OLS and Standard Errors">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Linear Regressions, OLS and Standard Errors</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../app_metrics/app_metrics9.html" class="pagination-link" aria-label="Quantile regressions with multiple fixed effects">
        <span class="nav-page-text">Quantile regressions with multiple fixed effects</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb30" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "DID: Panel Data &amp; Repeated Crossection"</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Using `CSDID` and `JWDID`"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## First Things First</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="fu">### DID with Multiple Periods and Time Heterogeneity</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>If you are reading this, you probably know quite well all the problems associated with the infamous TWFE-DID especification. Nevertheless, its worth a quick recap, in case you are not aware of.</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>Before the new literature on DID, whenever people wanted to analyze treatment effects using a difference in differences approach, and had access to data with many periods and many individuals, they would tend to use a model specification that look like this:</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>$$y_{it} = \delta_i + \delta_t + \gamma \times trt + e_{it}</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>$${#eq-1}</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>Where $trt$ was a dummy variable that would take the value of 1 for treated units after the treatment was implemented, and zero otherwise. The idea was that all units with $trt=0$ (those not yet treated) would be used used as controls. In this specification, one is also controlling for time fixed effects $\delta_t$ as well as individual (or group) fixed effects $\delta_i$.</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>This specification was considered a generalization of the simple 2x2 DID design:</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>y = \delta_0 + \delta_1 post+ \delta_2 treat + \gamma \ (post\times treat) + e_{it}</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>Where $\delta_i$ was the equivalent to $\delta_1$, and $\delta_2$ the equivalent for $\delta_t$.</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>What many didn't know at the time is that @eq-1 would provide correct identification of the Average treatment effect $\gamma$, under strict assumptions:</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is no treatment timing heterogeneity (All units are treated at the same time)</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>If there is timing heterogeneity, the treatment effect is homogenous across time and across groups. ($\gamma$ is the same across time or across groups)</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>This assumptions almost never hold. For example, the original treatment may become less effective few periods after they are implemented, and units treated later may experience stronger treatment effects than those treated earlier. When this happen, @eq-1 will provide incorrect results for three related reasons:</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Linear regressions do not discriminate between good or bad controls when identifying coefficients. They simply exploit all possible varation in the data. </span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Already treated units would be implicitly used as "control units", when analyzing units treated at a later point in time.</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Because of this, some treated units will receive "negative" weights, when estimating Average treatemnt effects.</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>One of the most interesting consequences of this problem is that one may estimate negative treatment effects, even if all units in the sample had a theoreticaly possitive treatment effect.</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>Many paper published in 2021 including @goodman_bacon_2021, @callaway_santanna_2021, @sun_estimating_2021, @wooldridge_twoway_2021 and @borusyak_revisiting_2022, to name a few, identified this problem, and proposed similar solutions: Estimate ATTs allowing for cohort and timing heterogeneity, avoiding the use of already treated units as controls. </span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>While these papers also provide their own estimators (in <span class="in">`Stata`</span>, <span class="in">`R`</span>, and in some cases <span class="in">`python`</span>), I will focus only on two solutions. The ones proposed by @callaway_santanna_2021 and @wooldridge_twoway_2021, which I programmed in <span class="in">`Stata`</span> using <span class="in">`csdid[2]`</span>, and <span class="in">`jwdid`</span>. Both approaches suggest to estimate heterogenous treatment effects based on when a unit is treated (its cohort $G$), and at what point in time one is interested in estimating that effect $T$. We will call them the $ATT(G,T)$. ^<span class="co">[</span><span class="ot">I will not provide details of the model specification in this post, but leave it for some future page on this site.</span><span class="co">]</span></span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a><span class="fu">##  GxT DID (instead  of 2x2 DID)</span></span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a><span class="fu">### Panel Data</span></span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>Lets assume you have access to Balanced Panel Data. In other words, you observe the same group of individuals across the same window of time. Different individuals are treated at different points in time, and some are not treated at all (never treated). This is the best case scenario, since you do not need to worry about identifying cohorts by treat timing. </span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>Let's see how to estimate this type of models using <span class="in">`csdid`</span> and <span class="in">`jwdid`</span>. They estimate the treatment effects using different strategies, but under specific cases, they will provide the same point estimates. To show how this is done, I will employ the toy-dataset used in @callaway_santanna_2021.</span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>First let's set things up, loading the data:</span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a><span class="in">*| output: false</span></span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a><span class="in">** to get the data from my repository</span></span>
<span id="cb30-61"><a href="#cb30-61" aria-hidden="true" tabindex="-1"></a><span class="in">ssc install frause, replace</span></span>
<span id="cb30-62"><a href="#cb30-62" aria-hidden="true" tabindex="-1"></a><span class="in">frause mpdta, clear</span></span>
<span id="cb30-63"><a href="#cb30-63" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-64"><a href="#cb30-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a>This dataset contains information at the county level on population size (lpop), employment (lemp), and a variable that indicates when a county instuted a change in minimum wage (first_treat). To estimate a DID model with heterogenous treatment effects, could use either <span class="in">`jwdid`</span> or <span class="in">`csdid`</span>, which are available from SSC.^<span class="co">[</span><span class="ot">If you want to use `csdid2`, please check the blog-post on using "own installer", and try `fra install csdid2`.</span><span class="co">]</span></span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-70"><a href="#cb30-70" aria-hidden="true" tabindex="-1"></a><span class="in">*| output: false</span></span>
<span id="cb30-71"><a href="#cb30-71" aria-hidden="true" tabindex="-1"></a><span class="in">** This is a dependency for csdid</span></span>
<span id="cb30-72"><a href="#cb30-72" aria-hidden="true" tabindex="-1"></a><span class="in">ssc install drdid, replace</span></span>
<span id="cb30-73"><a href="#cb30-73" aria-hidden="true" tabindex="-1"></a><span class="in">ssc install csdid, replace</span></span>
<span id="cb30-74"><a href="#cb30-74" aria-hidden="true" tabindex="-1"></a><span class="in">ssc install jwdid, replace</span></span>
<span id="cb30-75"><a href="#cb30-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-76"><a href="#cb30-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-77"><a href="#cb30-77" aria-hidden="true" tabindex="-1"></a>Just one more step (not required but important if you did not identified the <span class="in">`cohort`</span> variable). Lets create a dummy that takes the value of 1 only after the treated unit is treated:</span>
<span id="cb30-78"><a href="#cb30-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-81"><a href="#cb30-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-82"><a href="#cb30-82" aria-hidden="true" tabindex="-1"></a><span class="in">gen trt = (first_treat&lt;=year)*(first_treat&gt;0)</span></span>
<span id="cb30-83"><a href="#cb30-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-84"><a href="#cb30-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-85"><a href="#cb30-85" aria-hidden="true" tabindex="-1"></a>This is what @eq-1 is using. So how do I create the "*treatment cohort*" variable?. That can be easily done using one of <span class="in">`csdid`</span> subprograms. You just need to provide the group or panel identifier, and the time variable:</span>
<span id="cb30-86"><a href="#cb30-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-89"><a href="#cb30-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-90"><a href="#cb30-90" aria-hidden="true" tabindex="-1"></a><span class="in">egen gvar = csgvar(trt), ivar(countyreal) tvar(year)</span></span>
<span id="cb30-91"><a href="#cb30-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-92"><a href="#cb30-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-93"><a href="#cb30-93" aria-hidden="true" tabindex="-1"></a>Its worth noting that the official commands <span class="in">`xthdidregress`</span> and <span class="in">`hdidregress`</span> do not require you to do this, because it automatically creates the gvar internally, based on the information provided. You can now create a small tabulation, as a sanity check, to verity the variable <span class="in">`gvar`</span> is correctly created:</span>
<span id="cb30-94"><a href="#cb30-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-95"><a href="#cb30-95" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb30-96"><a href="#cb30-96" aria-hidden="true" tabindex="-1"></a><span class="in">tab year gvar</span></span>
<span id="cb30-97"><a href="#cb30-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-98"><a href="#cb30-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-99"><a href="#cb30-99" aria-hidden="true" tabindex="-1"></a>|year\gvar |         0    |   2004   |    2006   |    2007 |     Total|</span>
<span id="cb30-100"><a href="#cb30-100" aria-hidden="true" tabindex="-1"></a>|-----------|--------------|----------|-----------|---------|----------|</span>
<span id="cb30-101"><a href="#cb30-101" aria-hidden="true" tabindex="-1"></a>|      2003 |       309    |     20   |      40   |     131 |       500 |</span>
<span id="cb30-102"><a href="#cb30-102" aria-hidden="true" tabindex="-1"></a>|      2004 |       309    |     20   |      40   |     131 |       500 |</span>
<span id="cb30-103"><a href="#cb30-103" aria-hidden="true" tabindex="-1"></a>|      2005 |       309    |     20   |      40   |     131 |       500 |</span>
<span id="cb30-104"><a href="#cb30-104" aria-hidden="true" tabindex="-1"></a>|      2006 |       309    |     20   |      40   |     131 |       500 |</span>
<span id="cb30-105"><a href="#cb30-105" aria-hidden="true" tabindex="-1"></a>|      2007 |       309    |     20   |      40   |     131 |       500 |</span>
<span id="cb30-106"><a href="#cb30-106" aria-hidden="true" tabindex="-1"></a>|     Total |     1,545    |    100   |     200   |     655 |     2,500 |</span>
<span id="cb30-107"><a href="#cb30-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-108"><a href="#cb30-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-109"><a href="#cb30-109" aria-hidden="true" tabindex="-1"></a>If all goes as expected, you a tabulation similar to the one you see here. You have a total of 2500 observations, but only 500 counties. 309 were not treated (had no changes in minimum wage between 2003 and 2007), 20 were treated in 2004, 40 in 2006 and 131 in 2007.</span>
<span id="cb30-110"><a href="#cb30-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-111"><a href="#cb30-111" aria-hidden="true" tabindex="-1"></a>These numbers are what I call "effective sample size", because  <span class="in">`csdid`</span> (and implicitly <span class="in">`jwdid`</span>) use only this ammount of information when estimating the treatment effects. In other words, we should assume the sample size is 20 (for the purposes of model specification and controls).</span>
<span id="cb30-112"><a href="#cb30-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-113"><a href="#cb30-113" aria-hidden="true" tabindex="-1"></a>By default, <span class="in">`jwdid`</span> uses the not yet treated as comparison group. So, to make the results comparable to <span class="in">`csdid`</span>, I will request using those "never-treated" as comparison group. For <span class="in">`csdid`</span>, the default is using short gaps for pre-treatment ATT's, along with the never treated as comaprison group. To change that I will use <span class="in">`long2`</span> option. This will make the following comparable to the outcomes from standard Event-studies estimations. The next lines should produce identical point estimates, with very similar standard errors. </span>
<span id="cb30-114"><a href="#cb30-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-115"><a href="#cb30-115" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb30-116"><a href="#cb30-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-117"><a href="#cb30-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## CSDID</span></span>
<span id="cb30-118"><a href="#cb30-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-121"><a href="#cb30-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-122"><a href="#cb30-122" aria-hidden="true" tabindex="-1"></a><span class="in">csdid lemp , ivar(county) time(year) gvar(gvar) long2</span></span>
<span id="cb30-123"><a href="#cb30-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-124"><a href="#cb30-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-125"><a href="#cb30-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID</span></span>
<span id="cb30-126"><a href="#cb30-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-129"><a href="#cb30-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-130"><a href="#cb30-130" aria-hidden="true" tabindex="-1"></a><span class="in">jwdid lemp , ivar(county) time(year) gvar(gvar) never</span></span>
<span id="cb30-131"><a href="#cb30-131" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-132"><a href="#cb30-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-133"><a href="#cb30-133" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb30-134"><a href="#cb30-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-135"><a href="#cb30-135" aria-hidden="true" tabindex="-1"></a>You can of course add controls. In this case <span class="in">`lpop`</span> is a time constant variable, so it can be added to both commands. For us to obtain the same results, however, you need to add the <span class="in">`method(reg)`</span> to <span class="in">`csdid`</span>. Otherwise it will implement the double robust estimator <span class="in">`dripw`</span> (default)</span>
<span id="cb30-136"><a href="#cb30-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-137"><a href="#cb30-137" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb30-138"><a href="#cb30-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-139"><a href="#cb30-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## CSDID</span></span>
<span id="cb30-140"><a href="#cb30-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-143"><a href="#cb30-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-144"><a href="#cb30-144" aria-hidden="true" tabindex="-1"></a><span class="in">csdid lemp lpop , ivar(county) time(year) gvar(gvar) long2 method(reg)</span></span>
<span id="cb30-145"><a href="#cb30-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-146"><a href="#cb30-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-147"><a href="#cb30-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID</span></span>
<span id="cb30-148"><a href="#cb30-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-151"><a href="#cb30-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-152"><a href="#cb30-152" aria-hidden="true" tabindex="-1"></a><span class="in">jwdid lemp lpop, ivar(county) time(year) gvar(gvar) never </span></span>
<span id="cb30-153"><a href="#cb30-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-154"><a href="#cb30-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-155"><a href="#cb30-155" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb30-156"><a href="#cb30-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-157"><a href="#cb30-157" aria-hidden="true" tabindex="-1"></a>In general, however, you may not be interested in analyzing each individual ATTGT, but rather some aggregated results. For example, overall average, or dynamic effects.^<span class="co">[</span><span class="ot">also available `group` and `calendar`</span><span class="co">]</span>. Prof. Wooldrige, however, also suggest to ajust standard errors to account for sampling variation on the covariates. To do so, I need to modify the syntax of <span class="in">`jwdid`</span> slighly, as well as the post-estimation commands.</span>
<span id="cb30-158"><a href="#cb30-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-159"><a href="#cb30-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-160"><a href="#cb30-160" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb30-161"><a href="#cb30-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-162"><a href="#cb30-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## CSDID</span></span>
<span id="cb30-163"><a href="#cb30-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-166"><a href="#cb30-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-167"><a href="#cb30-167" aria-hidden="true" tabindex="-1"></a><span class="in">qui:csdid lemp lpop , ivar(county) time(year) gvar(gvar) long2 method(reg)</span></span>
<span id="cb30-168"><a href="#cb30-168" aria-hidden="true" tabindex="-1"></a><span class="in">estat simple</span></span>
<span id="cb30-169"><a href="#cb30-169" aria-hidden="true" tabindex="-1"></a><span class="in">estat event</span></span>
<span id="cb30-170"><a href="#cb30-170" aria-hidden="true" tabindex="-1"></a><span class="in">estat calendar</span></span>
<span id="cb30-171"><a href="#cb30-171" aria-hidden="true" tabindex="-1"></a><span class="in">estat group</span></span>
<span id="cb30-172"><a href="#cb30-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-173"><a href="#cb30-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-174"><a href="#cb30-174" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID</span></span>
<span id="cb30-175"><a href="#cb30-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-178"><a href="#cb30-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-179"><a href="#cb30-179" aria-hidden="true" tabindex="-1"></a><span class="in">qui:jwdid lemp lpop, ivar(county) time(year) gvar(gvar) never </span></span>
<span id="cb30-180"><a href="#cb30-180" aria-hidden="true" tabindex="-1"></a><span class="in">estat simple</span></span>
<span id="cb30-181"><a href="#cb30-181" aria-hidden="true" tabindex="-1"></a><span class="in">estat event</span></span>
<span id="cb30-182"><a href="#cb30-182" aria-hidden="true" tabindex="-1"></a><span class="in">estat calendar</span></span>
<span id="cb30-183"><a href="#cb30-183" aria-hidden="true" tabindex="-1"></a><span class="in">estat group</span></span>
<span id="cb30-184"><a href="#cb30-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-185"><a href="#cb30-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-186"><a href="#cb30-186" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID: vce(unconditional)</span></span>
<span id="cb30-187"><a href="#cb30-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-190"><a href="#cb30-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-191"><a href="#cb30-191" aria-hidden="true" tabindex="-1"></a><span class="in">qui:jwdid lemp lpop, ivar(county) time(year) gvar(gvar) never ///</span></span>
<span id="cb30-192"><a href="#cb30-192" aria-hidden="true" tabindex="-1"></a><span class="in">    method(regress) group</span></span>
<span id="cb30-193"><a href="#cb30-193" aria-hidden="true" tabindex="-1"></a><span class="in">estat simple, vce(unconditional)</span></span>
<span id="cb30-194"><a href="#cb30-194" aria-hidden="true" tabindex="-1"></a><span class="in">estat event, vce(unconditional)</span></span>
<span id="cb30-195"><a href="#cb30-195" aria-hidden="true" tabindex="-1"></a><span class="in">estat calendar, vce(unconditional)</span></span>
<span id="cb30-196"><a href="#cb30-196" aria-hidden="true" tabindex="-1"></a><span class="in">estat group, vce(unconditional)</span></span>
<span id="cb30-197"><a href="#cb30-197" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-198"><a href="#cb30-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-199"><a href="#cb30-199" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb30-200"><a href="#cb30-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-201"><a href="#cb30-201" aria-hidden="true" tabindex="-1"></a>Again, both showing identical point estimates with slighly different standard errors. </span>
<span id="cb30-202"><a href="#cb30-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-203"><a href="#cb30-203" aria-hidden="true" tabindex="-1"></a><span class="fu">## Repeated Crossection</span></span>
<span id="cb30-204"><a href="#cb30-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-205"><a href="#cb30-205" aria-hidden="true" tabindex="-1"></a>Repeated crossection operates slighly different than panel data. On the one hand, you do not observe the same units across time. Thus, there is no *unit specific fixed-effect*. Instead one would be trying to account for cohort specific effect, or treatment-level fixed effects. This may become clearer with an example. </span>
<span id="cb30-206"><a href="#cb30-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-207"><a href="#cb30-207" aria-hidden="true" tabindex="-1"></a>Lets us first consider the same dataset as before. To simulate the situation of repeated crossection, lets assume that each round, data was collected for a random sample of counties within each State, and that, for some unknown reason, we cannot identify counties across time. Lets us also assume that the treatment was implemented at the State level (for clustering purposes). First some data preparation.</span>
<span id="cb30-208"><a href="#cb30-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-209"><a href="#cb30-209" aria-hidden="true" tabindex="-1"></a>To simulate repeated crossection structure, I will drop 10% of the data, create a ***State id***, and drop the county identifier.  </span>
<span id="cb30-210"><a href="#cb30-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-213"><a href="#cb30-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-214"><a href="#cb30-214" aria-hidden="true" tabindex="-1"></a><span class="in">** load and obtain trt</span></span>
<span id="cb30-215"><a href="#cb30-215" aria-hidden="true" tabindex="-1"></a><span class="in">frause mpdta, clear</span></span>
<span id="cb30-216"><a href="#cb30-216" aria-hidden="true" tabindex="-1"></a><span class="in">gen trt = (first_treat&lt;=year)*(first_treat&gt;0)</span></span>
<span id="cb30-217"><a href="#cb30-217" aria-hidden="true" tabindex="-1"></a><span class="in">gen state = int(countyreal/1000)</span></span>
<span id="cb30-218"><a href="#cb30-218" aria-hidden="true" tabindex="-1"></a><span class="in">** Randomly keep 90% of the data</span></span>
<span id="cb30-219"><a href="#cb30-219" aria-hidden="true" tabindex="-1"></a><span class="in">set seed 1</span></span>
<span id="cb30-220"><a href="#cb30-220" aria-hidden="true" tabindex="-1"></a><span class="in">sample 90</span></span>
<span id="cb30-221"><a href="#cb30-221" aria-hidden="true" tabindex="-1"></a><span class="in">drop countyreal</span></span>
<span id="cb30-222"><a href="#cb30-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-223"><a href="#cb30-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-224"><a href="#cb30-224" aria-hidden="true" tabindex="-1"></a>Next is to create the <span class="in">`gvar`</span>. This will follow the same syntax as before, with the main difference that instead of using **countyreal** as <span class="in">`ivar`</span>, we will use <span class="in">`state`</span>. Its important that this variable represents the identifier of the level at which the treatment was implemented, and that we can follow up across time. </span>
<span id="cb30-225"><a href="#cb30-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-228"><a href="#cb30-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-229"><a href="#cb30-229" aria-hidden="true" tabindex="-1"></a><span class="in">egen gvar = csgvar(trt), ivar(state) tvar(year)</span></span>
<span id="cb30-230"><a href="#cb30-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-231"><a href="#cb30-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-232"><a href="#cb30-232" aria-hidden="true" tabindex="-1"></a>And as always, its a good idea to crosstabulate year with the new gvar:</span>
<span id="cb30-233"><a href="#cb30-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-234"><a href="#cb30-234" aria-hidden="true" tabindex="-1"></a><span class="in">```stata</span></span>
<span id="cb30-235"><a href="#cb30-235" aria-hidden="true" tabindex="-1"></a><span class="in">tab year gvar</span></span>
<span id="cb30-236"><a href="#cb30-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-237"><a href="#cb30-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-238"><a href="#cb30-238" aria-hidden="true" tabindex="-1"></a>|year\gvar |         0    |   2004   |    2006   |    2007 |     Total|</span>
<span id="cb30-239"><a href="#cb30-239" aria-hidden="true" tabindex="-1"></a>|-----------|--------------|----------|-----------|---------|----------|</span>
<span id="cb30-240"><a href="#cb30-240" aria-hidden="true" tabindex="-1"></a>|      2003 |       279    |     19    |     35    |    114 |       447 |</span>
<span id="cb30-241"><a href="#cb30-241" aria-hidden="true" tabindex="-1"></a>|      2004 |       286    |     19    |     34    |    117 |       456 |</span>
<span id="cb30-242"><a href="#cb30-242" aria-hidden="true" tabindex="-1"></a>|      2005 |       279    |     18    |     38    |    121 |       456 |</span>
<span id="cb30-243"><a href="#cb30-243" aria-hidden="true" tabindex="-1"></a>|      2006 |       275    |     18    |     40     |   115 |       448 |</span>
<span id="cb30-244"><a href="#cb30-244" aria-hidden="true" tabindex="-1"></a>|      2007 |       275    |     18    |     36      |  114 |       443 |</span>
<span id="cb30-245"><a href="#cb30-245" aria-hidden="true" tabindex="-1"></a>|     Total |     1,474     |    93   |     193     |   615 |     2,375 |</span>
<span id="cb30-246"><a href="#cb30-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-247"><a href="#cb30-247" aria-hidden="true" tabindex="-1"></a>What you should observe, as shown here, is that you still have roughtly the same number of observations per <span class="in">`gvar`</span> across time. This is important because you need to have a groups that are comparable across time. Think of this as having a pseudo panel. </span>
<span id="cb30-248"><a href="#cb30-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-249"><a href="#cb30-249" aria-hidden="true" tabindex="-1"></a>In terms of estimation, the syntax needs to be adjusted slighly:</span>
<span id="cb30-250"><a href="#cb30-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-251"><a href="#cb30-251" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb30-252"><a href="#cb30-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-253"><a href="#cb30-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## CSDID</span></span>
<span id="cb30-254"><a href="#cb30-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-255"><a href="#cb30-255" aria-hidden="true" tabindex="-1"></a>If you are using <span class="in">`csdid`</span>, the adjustment simply requires to drop <span class="in">`ivar`</span> option. To make sure we are clustering at the correct level, one should use <span class="in">`cluster()`</span> instead, using the pseudo panel identifier <span class="in">`state`</span> as clustering variable:</span>
<span id="cb30-256"><a href="#cb30-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-259"><a href="#cb30-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-260"><a href="#cb30-260" aria-hidden="true" tabindex="-1"></a><span class="in">csdid lemp , cluster(state) time(year) gvar(gvar) long2</span></span>
<span id="cb30-261"><a href="#cb30-261" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-262"><a href="#cb30-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-263"><a href="#cb30-263" aria-hidden="true" tabindex="-1"></a>Aggregations are obtained using <span class="in">`estat`</span> post estimation commnads.</span>
<span id="cb30-264"><a href="#cb30-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-265"><a href="#cb30-265" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID-I</span></span>
<span id="cb30-266"><a href="#cb30-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-267"><a href="#cb30-267" aria-hidden="true" tabindex="-1"></a>If you are using <span class="in">`jwdid`</span>, there are two alternatives. The first one is to use <span class="in">`ivar()`</span> with the new pseudo panel identifier (<span class="in">`state`</span>).</span>
<span id="cb30-268"><a href="#cb30-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-271"><a href="#cb30-271" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-272"><a href="#cb30-272" aria-hidden="true" tabindex="-1"></a><span class="in">jwdid lemp , ivar(state) time(year) gvar(gvar) never</span></span>
<span id="cb30-273"><a href="#cb30-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-274"><a href="#cb30-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-275"><a href="#cb30-275" aria-hidden="true" tabindex="-1"></a>Data will be clustered at the state level, explicitly accounting for State fixed effects.</span>
<span id="cb30-276"><a href="#cb30-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-277"><a href="#cb30-277" aria-hidden="true" tabindex="-1"></a><span class="fu">## JWDID-II</span></span>
<span id="cb30-278"><a href="#cb30-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-279"><a href="#cb30-279" aria-hidden="true" tabindex="-1"></a>Alternatively, one could change <span class="in">`ivar()`</span> with <span class="in">`cluster()`</span>, to ensure clustering is done at the correct level, and add the option <span class="in">`group`</span>, so that cohort fixed effects are added to the specification.^<span class="co">[</span><span class="ot">In my repository, the newer version of `jwdid` does this automatically if `ivar()` is not provided.</span><span class="co">]</span></span>
<span id="cb30-280"><a href="#cb30-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-283"><a href="#cb30-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{stata}</span></span>
<span id="cb30-284"><a href="#cb30-284" aria-hidden="true" tabindex="-1"></a><span class="in">jwdid lemp , cluster(state) time(year) gvar(gvar) never group</span></span>
<span id="cb30-285"><a href="#cb30-285" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-286"><a href="#cb30-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-287"><a href="#cb30-287" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb30-288"><a href="#cb30-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-289"><a href="#cb30-289" aria-hidden="true" tabindex="-1"></a>The results across the different approaches will be different because of how the data is used. But, as you can see here, point estimates are broadly comparable. </span>
<span id="cb30-290"><a href="#cb30-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-291"><a href="#cb30-291" aria-hidden="true" tabindex="-1"></a>As far as I know, either option is correct.</span>
<span id="cb30-292"><a href="#cb30-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-293"><a href="#cb30-293" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusions</span></span>
<span id="cb30-294"><a href="#cb30-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-295"><a href="#cb30-295" aria-hidden="true" tabindex="-1"></a>I hope this reference helps people who want to use <span class="in">`jwdid`</span> and <span class="in">`csdid`</span> for the estimation of DID models in the presence of repeated crossection.</span>
<span id="cb30-296"><a href="#cb30-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-297"><a href="#cb30-297" aria-hidden="true" tabindex="-1"></a>If you have comments, or questions, do not hesitate to contact me.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>