{
  "hash": "d3f10bae98047ea2ac7c0de8286225ca",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Quarto 1.4\"\ndescription: \"Some examples for Table cross-referencing!\"\nauthor: \"Fernando Rios-Avila\"\ndate: \"01/25/2024\"\ncategories: \n    - Quarto\ndraft: false\nformat:\n    html: default\n    pdf: default\n---\n\nQuarto 1.4 is out! Over the last few weeks, they have been pushing quite few updates, and finally they have released version 1.4. \n\nWhat is quite interesting to me is that this version includes a new feature that I have been waiting for a while: Multi source cross-referencing!\n\nI have been using Quarto for some time now, and one of the things I noticed is that it was very easy to add titles and cross-references to tables as long as they were formated as markdown tables. \n\nHowever, as you may now, markdown tables are not very flexible. Better options include HTML tables, and even better, LaTeX tables. Unfortunately, there was no easy way to reference those kinds of tables using the `@ref` syntax. Looking at other people's questions and solutions, they all seemed a bit complicated to me. (specially those that involved using LaTeX commands).\n\nBut now, with version 1.4, it seems very easy to reference tables that are not markdown tables!\n\nLet's see how it works!\n\n## Setup\n\nTo do this, I will produce a simple regression using `Stata`, and export it as markdown, HTML, and LaTeX tables using `esttab`^[`esttab` is part of `estout` package by Ben Jann.]. \n\n::: {.cell execution_count=1}\n``` {.stata .cell-code code-fold=\"false\"}\nfrause oaxaca, clear\nqui:reg  lnwage educ exper tenure female\nest sto m1\nqui:reg  lnwage educ exper tenure female age agesq married divorced\nest sto m2\n\nesttab m1 m2 using \"reg_md\", wide se replace md\nesttab m1 m2 using \"reg_html\", wide se replace htm\nesttab m1 m2 using \"reg_tex\", wide se replace tex\n```\n\n::: {.cell-output .cell-output-display}\n```\n<IPython.core.display.HTML object>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n(Excerpt from the Swiss Labor Market Survey 1998)\n(output written to reg_md.md)\n(output written to reg_html.html)\n(output written to reg_tex.tex)\n```\n:::\n:::\n\n\nThe output of the code is not usable right away, as it has some minor issues. For example, the markdown table has an extra line that needs to be removed. \n\n## Markdown table\n\nFor the next I will make it simple, using what I think is the easiest cross reference the tables:\n\n```markdown\n::: {#tbl-table1}\n{{{< include reg_md.md >}}}\nTable made with markdown\n:::\n```\n\nGeneral syntax: \n\n- line 1 indicates we will be creating table that could be referenced using `@tbl-table1` code.\n- line 2 request to \"include\"  the markdown table file.\n- line 3 is the title of this table\n\nThe result is the following table:\n\n::: {#tbl-table1}\n\n|              |          (1)                  |              |          (2)                  |              |\n| ------------ | :---------------------------: | :----------: | :---------------------------: | :----------: |\n| educ         |       0.0848<sup>\\*\\*\\*</sup> |    (0.00519) |       0.0644<sup>\\*\\*\\*</sup> |    (0.00508) |\n| exper        |       0.0111<sup>\\*\\*\\*</sup> |    (0.00154) |    -0.000311                  |    (0.00181) |\n| tenure       |      0.00771<sup>\\*\\*\\*</sup> |    (0.00188) |      0.00672<sup>\\*\\*\\*</sup> |    (0.00190) |\n| female       |      -0.0841<sup>\\*\\*\\*</sup> |     (0.0251) |       -0.160<sup>\\*\\*\\*</sup> |     (0.0243) |\n| age          |                               |              |        0.113<sup>\\*\\*\\*</sup> |    (0.00814) |\n| agesq        |                               |              |     -0.00126<sup>\\*\\*\\*</sup> |  (0.0000976) |\n| married      |                               |              |      -0.0224                  |     (0.0294) |\n| divorced     |                               |              |       0.0719                  |     (0.0412) |\n| \\_cons       |        2.213<sup>\\*\\*\\*</sup> |     (0.0683) |        0.311<sup>\\*</sup>     |      (0.149) |\n| *N*          |         1434                  |              |         1434                  |              |\n\n \n\n\nTable made with markdown\n:::\n\nThis one was already feasible before however.\n\n## HTML table\n\nNow, let's try with an HTML table. The syntax is very similar:\n\n```markdown\n    ::: {#tbl-table2}\n    ````{=html}\n    {{{< include reg_html.html >}}}\n    ````\n    Table made with markdown\n    :::\n```\n\nwith the following result:\n\n::: {#tbl-table2}\n\n\n```{=html}\n<table border=\"0\" width=\"*\">\n<tr><td colspan=5><hr></td></tr>\n<tr><td>            </td><td>         (1)              </td><td>            </td><td>         (2)              </td><td>            </td></tr>\n<tr><td>            </td><td>      lnwage              </td><td>            </td><td>      lnwage              </td><td>            </td></tr>\n<tr><td colspan=5><hr></td></tr>\n<tr><td>educ        </td><td>      0.0848<sup>***</sup></td><td>   (0.00519)</td><td>      0.0644<sup>***</sup></td><td>   (0.00508)</td></tr>\n<tr><td>exper       </td><td>      0.0111<sup>***</sup></td><td>   (0.00154)</td><td>   -0.000311              </td><td>   (0.00181)</td></tr>\n<tr><td>tenure      </td><td>     0.00771<sup>***</sup></td><td>   (0.00188)</td><td>     0.00672<sup>***</sup></td><td>   (0.00190)</td></tr>\n<tr><td>female      </td><td>     -0.0841<sup>***</sup></td><td>    (0.0251)</td><td>      -0.160<sup>***</sup></td><td>    (0.0243)</td></tr>\n<tr><td>age         </td><td>                          </td><td>            </td><td>       0.113<sup>***</sup></td><td>   (0.00814)</td></tr>\n<tr><td>agesq       </td><td>                          </td><td>            </td><td>    -0.00126<sup>***</sup></td><td> (0.0000976)</td></tr>\n<tr><td>married     </td><td>                          </td><td>            </td><td>     -0.0224              </td><td>    (0.0294)</td></tr>\n<tr><td>divorced    </td><td>                          </td><td>            </td><td>      0.0719              </td><td>    (0.0412)</td></tr>\n<tr><td>_cons       </td><td>       2.213<sup>***</sup></td><td>    (0.0683)</td><td>       0.311<sup>*</sup>  </td><td>     (0.149)</td></tr>\n<tr><td colspan=5><hr></td></tr>\n<tr><td><i>N</i>    </td><td>        1434              </td><td>            </td><td>        1434              </td><td>            </td></tr>\n<tr><td colspan=5><hr></td></tr>\n<tr><td colspan=5>\nStandard errors in parentheses\n<br /><sup>*</sup> <i>p</i> < 0.05, <sup>**</sup> <i>p</i> < 0.01, <sup>***</sup> <i>p</i> < 0.001\n</td></tr>\n</table>\n\n```\n\n\nTable made with HTML\n:::\n\nNow, there is a small difference in the produced table because how `esttab` produces the HTML table. Neverthless, the table creation and naming works!\n\nAlso, notice that I'm adding a code chunk `=html`, so the information can be read correctly.\n\n## LaTeX table\n\nFinally, let's try with a LaTeX table. The syntax is very similar:\n\n```markdown\n::: {#tbl-table3}\n{{{< include reg_tex.tex >}}}\nTable made with Latex\n:::\n```\n\nwith the following result:\n\n::: {#tbl-table3}\n\n\\def\\sym#1{\\ifmmode^{#1}\\else\\(^{#1}\\)\\fi}\n\\begin{tabular}{l*{2}{cc}}\n\\hline\\hline\n            &\\multicolumn{2}{c}{(1)}           &\\multicolumn{2}{c}{(2)}           \\\\\n            &\\multicolumn{2}{c}{lnwage}        &\\multicolumn{2}{c}{lnwage}        \\\\\n\\hline\neduc        &      0.0848\\sym{***}&   (0.00519)&      0.0644\\sym{***}&   (0.00508)\\\\\nexper       &      0.0111\\sym{***}&   (0.00154)&   -0.000311         &   (0.00181)\\\\\ntenure      &     0.00771\\sym{***}&   (0.00188)&     0.00672\\sym{***}&   (0.00190)\\\\\nfemale      &     -0.0841\\sym{***}&    (0.0251)&      -0.160\\sym{***}&    (0.0243)\\\\\nage         &                     &            &       0.113\\sym{***}&   (0.00814)\\\\\nagesq       &                     &            &    -0.00126\\sym{***}& (0.0000976)\\\\\nmarried     &                     &            &     -0.0224         &    (0.0294)\\\\\ndivorced    &                     &            &      0.0719         &    (0.0412)\\\\\n\\_cons      &       2.213\\sym{***}&    (0.0683)&       0.311\\sym{*}  &     (0.149)\\\\\n\\hline\n\\(N\\)       &        1434         &            &        1434         &            \\\\\n\\hline\\hline\n\\multicolumn{5}{l}{\\footnotesize Standard errors in parentheses}\\\\\n\\multicolumn{5}{l}{\\footnotesize \\sym{*} \\(p<0.05\\), \\sym{**} \\(p<0.01\\), \\sym{***} \\(p<0.001\\)}\\\\\n\\end{tabular}\n\n\n\nTable made with Latex\n:::\n\nAhh! seems this is not working! The reason is that Latex tables do not render in html. However if you look into the [pdf version](reg1.pdf), you will see that the table is there, and it is correctly named!\n\nIn contrast, the HTML code may not render in the pdf version.\n\n## Cross-referencing\n\nAs you can see @tbl-table1 was done with md, @tbl-table2 with html and @tbl-table3 with LaTeX.\n\n",
    "supporting": [
      "index_files\\figure-pdf"
    ],
    "filters": []
  }
}