---
title: "Matching and Re-weighting"
subtitle: "When X differ..."
author: Fernando Rios-Avila
format:
  revealjs: 
    slide-number: true
    width: 1500
    height: 900
    code-overflow: scroll
    theme: simple
jupyter: nbstata
---

## Recap: Potential outcomes and Identification

To identify treatment effects one could just compare potential outcomes in two states:

 - with treatment
 - without treament

Mathematically:
$$
ATE = E(Y_i(1)-Y_i(0))
$$

the problem: with real data, we are only able to see one outcome. The counterfactual is not observed:

$$
Y_i = Y_i(1)*D + Y_i(0)*(1-D)
$$

and simple differences may not capture ATE, because of selection bias and heterogeneity

## Recap: Gold Standard - RCT

The easiest, but most expensive, way to deal with the problem is using **Randomized Control Trials**.

Effectily, you randomize Treatment, so that potential outcomes are independent of treatment:

$$Y(1),Y(0) \perp D
$$

In other words, the distribution of potential outcomes is the same for those treated or untreated units.

$$
\begin{aligned}
E(Y,D=1)&=E(Y(1),D=1)=E(Y(1),D=0) \\
E(Y,D=0)&=E(Y(0),D=1)=E(Y(0),D=0) \\
ATT&=E(Y,D=1) - E(Y,D=0)
\end{aligned}
$$

# But what if you can't Randomize {background-color="#447099"}

## When unconditional fails

More often than not, specially if we didnt construct the data, it would be impossible to find that unconditional independence assumption holds. 

For example, treatment (say having health insurance) may vary by age, gender, race, location, etc.

This is similar to the selection bias: Outcomes across treated and untreated groups will be different because of:

- Treatment 

- Composition: Characteristics of people among the treated could be different than those among the untreated
    For example, they could be older, more educated, mostly men, etc.

- Other factors: There could be factors we cannot control for, that also affect outcomes.

## There is conditional

When unconditional independence assumption fails, we can call on Conditional independence assumption:

$$
Y(1),Y(0) \perp D | X
$$

In other words, If we can look into specific groups (given $X$), it may be possible to impose the Independence assumption.

This relaxes the independence condition, but assumes selection is due to observable characteristics only.
(but it still needs to be as good as randomized)

Implications:

$$
\begin{aligned}
E(Y|D=1,X) =E(Y(1)|D=1,X)=E(Y(1)|D=0,X)  \\
E(Y|D=0,X) =E(Y(0)|D=1,X)=E(Y(0)|D=0,X) 
\end{aligned}
$$

## Intuition

Matching is a methodology that falls within quasi-experimental designs. You cannot or could not decide the assigment rules, so now are using data as given.

The idea is to construct an artificial control and use it as a counterfactual, so that both treated and control groups "look the same". 

Once a group of syntethic controls has been constructed, treatment effects can be calculated for the whole population:

$$
\begin{aligned}
ATE(X) &= E(Y|D=1,X) -E(Y|D=0,X) \\
ATE &= \int ATE(X) dFx 
\end{aligned}
$$

How can we do this?

## Subclassification or stratification

Consider the following dataset:

```{stata}
frause titanic, clear
gen class1=class==1
tab survived class1  [iw=freq], nofreq col
```
If we assume full Independence assumption we would  believe that being in first class increased chance of survival in 35.4%. but is that the case?

What if the composition of individuals change across classes (women and children)

```{stata}
frause titanic, clear
gen class1=class==1
tab age class1  [iw=freq], nofreq col
tab sex class1  [iw=freq], nofreq col
```
There were fewer children, but more women in first class. Perhaps that explains the difference in survival rates



